pipeline:
  audit:
    image: node:8
    commands:
      - npm install
      - npm audit fix
      - npm audit fix --force
      - rm -rf node_modules
  docker:
    image: plugins/docker
    registry: dhub.promise.com.tw:5000
    repo: dhub.promise.com.tw:5000/applications/codibook
    insecure: true
    username: cibot
    password: Promise123!
    dockerfile: Dockerfile
    auto_tag: true
  line:
    image: appleboy/drone-line
    channel_secret: cd7614ad206999ea0c04e9b07726ac90
    channel_token: jZBrOrguiHyCk8bFyQpPZy6iX5AxLZiR5DS92bQThh/KKS/eKzA9xvKZIElRANeI8OM+Esr+2hJc2mr9r5Nt/OPOjf64Cs5mNQ3nPqUTq4J1W/KlIpb4QL3asj7Oy3sLQbvkqmlAQSh3V8lVkmwZBAdB04t89/1O/w1cDnyilFU=
    to: U9cedeb21fa7a7dca29bad0615506b611