pipeline:
  audit:
    image: node:8
    commands:
      - npm install
      - npm audit fix
  docker:
    image: plugins/docker
    registry: dhub.promise.com.tw:5000
    repo: dhub.promise.com.tw:5000/applications/codibook
    insecure: true
    username: cibot
    password: Promise123!
    dockerfile: Dockerfile
    auto_tag: true